<head>
	<title><?php echo 'A'?></title>
	<script src="/js/jquery-1.6.2.min.js"></script>
</head>
<table>
<?php foreach ($this->tables as $table => $families): ?>
	<tr>
		<td>
			<a href="/admin/db/table/name/<?php echo $table?>"><?php echo $table?></a>
		</td>
		<td>
		<?php foreach ($families as $family): ?>
			<a class='families' href="/admin/db/table/name/<?php echo $table?>/cf/<?php echo $family?>"><?php echo $family?></a>
		<?php endforeach ?>
			<span class="navigation">
				<a link="/admin/db/row/table/<?php echo $table ?>/id/" href="/admin/db/row/table/<?php echo $table ?>/id/1">id</a>
				<input type="text" class="input" id="<?php echo $table ?>" value=""/>
			</span>

			<div class="clear"></div>

		</td>
		<td><a class="only" href="/admin/db/table/name/<?php echo $table?>/only/1">Ids only</a></td>
	</tr>
<?php endforeach ?>
</table>
<style type="text/css">

	span.navigation {
		float: right;
	}

	span.navigation input.input {
		width: 35px;
		font-size: 70%;
		background: #ccc;
	}

	a.families {
		float: left;
		width: 140px;
		border: 1px green solid;
		display: block;
		margin: 2px;
	}

	a.only {
		border: 1px red solid;
		display: block;
		margin: 2px;
		background: #ccc;
	}

	div.clear {
		clear: both;
	}

	table, tr, td {
		border: 1px solid black;
	}
</style>
<script type="text/javascript">
	$(document).ready(function()
	{
		$('span.navigation > input').keyup(function(evt)
		{
			var input = $(this);
			var a = input.prev('a');
			var href = a.attr('link') + input.val();

			a.attr('href',href);
		});
		$('span.navigation > input').keypress(function(e)
		{
			var code = (e.keyCode ? e.keyCode : e.which);
			if(code == 13)
			{
				window.location.href = $(this).prev('a').attr('href');
			}
		})
	});
</script>