<?php
header('Content-Type: text/html; charset=utf-8');
echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<link rel="shortcut icon" href="favicon.ico" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Admin</title>
  <link rel="stylesheet" type="text/css" href="/css/admin/admin.css" />
  <?php echo $this->headScript();?>
</head>
<body>

<?php echo $this->layout()->content ?>

</body>
</html>